### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isPathIgnored' of null

### ISSUE THREAD

**Issue by kanedauy** [atom-community/autocomplete-paths#111]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) package 2.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'isPathIgnored' of null

```
At /Users/asuero/.atom/packages/autocomplete-paths/lib/paths-cache.js:30

TypeError: Cannot read property 'isPathIgnored' of null
    at /packages/autocomplete-paths/lib/paths-cache.js:30:21
    at Array.forEach (native)
    at PathsCache._isPathIgnored (/packages/autocomplete-paths/lib/paths-cache.js:29:24)
    at Object.filter (/packages/autocomplete-paths/lib/paths-cache.js:90:36)
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:239:42
    at Array.filter (native)
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:236:12
    at /packages/autocomplete-paths/node_modules/readdirp/readdirp.js:199:38
    at /Applications/Atom.app/Contents/Resources/app/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -1:39.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.30.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
aurora-theme 1.2.2 
autocomplete-modules 1.6.10 
autocomplete-paths 2.0.0 
busy-signal 1.4.3 
colorblind-wombat-dark-syntax 0.6.0 
custom-title 1.0.1 
docblockr 0.11.0 
file-icons 2.1.10 
gloom 0.6.4 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-docker 1.1.8 
linter 2.2.0 
linter-docker 0.2.0 
linter-js-yaml undefined 
linter-jshint 3.1.5 
linter-jsonlint 1.3.0 
linter-pug 1.3.1 
linter-swagger 0.4.1 
linter-ui-default 1.6.4 
markdown-preview-plus 2.4.10 
MavensMate-Atom 1.0.10 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
pigments 0.40.2 
ramda-syntax 1.0.4 
```

**Comment by saschagehlich** [comment]
Thanks - fixed in 2.0.1
