### ISSUE TITLE
Updating to autocomplete-paths@2.0.2 failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by kylebarron** [atom-community/autocomplete-paths#115]
I saw a similar [issue](https://github.com/atom-community/autocomplete-paths/issues/113) on Windows, and thought I'd create a new issue to make clear that this exists on Ubuntu as well.

```bash
> apm update
Package Updates Available (1)
└── autocomplete-paths 1.0.5 -> 2.0.2

Would you like to install these updates? (yes) yes

Installing autocomplete-paths@2.0.2 to /home/kyle/.atom/packages ✗

> runas@3.1.1 install /tmp/apm-install-dir-117711-19585-a02aww.q9h6txd2t9/node_modules/autocomplete-paths/node_modules/runas
> node-gyp rebuild

/tmp/apm-install-dir-117711-19585-a02aww.q9h6txd2t9
└── (empty)


npm WARN excluding symbolic link spec/fixtures/linkeddir -> ./somedir
npm WARN excluding symbolic link spec/fixtures/linkeddir -> ./somedir
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Linux 4.10.0-30-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-117711-19585-a02aww.q9h6txd2t9/node_modules/autocomplete-paths/node_modules/runas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-117711-19585-a02aww.q9h6txd2t9/package.json'
npm WARN apm-install-dir-117711-19585-a02aww.q9h6txd2t9 No description
npm WARN apm-install-dir-117711-19585-a02aww.q9h6txd2t9 No repository field.
npm WARN apm-install-dir-117711-19585-a02aww.q9h6txd2t9 No README data
npm WARN apm-install-dir-117711-19585-a02aww.q9h6txd2t9 No license field.
npm ERR! Linux 4.10.0-30-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/kyle/.atom/.apm/.apmrc" "--userconfig" "/home/kyle/.atom/.apmrc" "install" "/tmp/d-117711-19585-1ys5kgn.lxuaj7nwmi/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-117711-19585-a02aww.q9h6txd2t9/npm-debug.log
npm ERR! code 1
```

```bash
> atom --version
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by albireox** [comment]
Same problem on Mac.

**Comment by saschagehlich** [comment]
Version 2.1.0 now uses atom's built-in (precompiled) version of `pathwatcher` which should fix this issue. Please check it out!

**Comment by kylebarron** [comment]
That worked! Thanks!
