### ISSUE TITLE
Uncaught TypeError: Cannot read property 'files' of undefined

### ISSUE THREAD

**Issue by rssawhney** [atom-community/autocomplete-paths#116]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) package 2.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'files' of undefined

```
At /home/papajohn/.atom/packages/autocomplete-paths/lib/paths-cache.js:199

TypeError: Cannot read property 'files' of undefined
    at PathsCache.getFilesForProjectPath (/packages/autocomplete-paths/lib/paths-cache.js:199:76)
    at PathsProvider._getSuggestionsForScope (/packages/autocomplete-paths/lib/paths-provider.js:98:34)
    at /packages/autocomplete-paths/lib/paths-provider.js:166:49
    at Array.map (native)
    at PathsProvider.getSuggestions (/packages/autocomplete-paths/lib/paths-provider.js:166:29)
    at /usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -2:14.6.0 application:add-project-folder (input.hidden-input)
  2x -1:57.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-syntax.theme-dracula-ui)
  2x -1:35.5.0 core:backspace (input.hidden-input)
     -1:27.1.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-save-all 0.4.1 
atom-ternjs 0.18.3 
autocomplete-paths 2.0.2 
busy-signal 1.4.3 
color-picker 2.2.5 
dracula-syntax 2.0.5 
dracula-ui 0.6.0 
file-icons 2.1.10 
flow-ide 1.8.1 
git-plus 7.9.3 
goto-definition 1.3.4 
highlight-selected 0.13.1 
hyperclick 0.1.3 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.2.1 
linter-jscs 4.1.2 
linter-jshint 3.1.5 
linter-rubocop 2.1.1 
linter-ui-default 1.6.4 
pigments 0.40.2 
project-manager 3.3.5 
sync-settings 0.8.2 
terminal-fusion 2.4.4 
```

**Comment by saschagehlich** [comment]
*Should* be fixed with 2.1.0 - please check it out!

**Comment by saschagehlich** [comment]
Closing this for now. Please re-open if issue persists.

**Comment by rssawhney** [comment]
It's fixed, Thanks mate
