### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by francisngo** [atom-community/autocomplete-paths#125]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) package 2.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /Users/sicnarf/.atom/packages/autocomplete-paths/lib/paths-provider.js:121

TypeError: Cannot read property 'path' of null
    at PathsProvider._getSuggestionsForScope (/packages/autocomplete-paths/lib/paths-provider.js:121:65)
    at /packages/autocomplete-paths/lib/paths-provider.js:211:12
    at Array.map (native)
    at PathsProvider.getSuggestions (/packages/autocomplete-paths/lib/paths-provider.js:210:30)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -4:31.9.0 core:save (input.hidden-input)
  2x -4:29 core:backspace (input.hidden-input)
     -4:28.2.0 core:move-right (input.hidden-input)
     -4:27.8.0 core:backspace (input.hidden-input)
     -4:27.5.0 core:save (input.hidden-input)
     -4:25.9.0 tree-view:toggle (input.hidden-input)
     -4:21.2.0 tree-view:remove (span.name.icon.js-icon.medium-yellow)
     -4:06.1.0 core:confirm (input.hidden-input)
     -3:26.2.0 window:toggle-dev-tools (input.hidden-input)
  2x -1:03.9.0 tree-view:remove (li.file.entry.list-item.selected)
     -0:55.5.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:51.4.0 tree-view:add-folder (div.header.list-item)
     -0:49.5.0 core:confirm (input.hidden-input)
     -0:45.8.0 tree-view:toggle (input.hidden-input)
     -0:41.3.0 core:move-left (input.hidden-input)
     -0:39.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
autocomplete-paths 2.4.0 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.10 
floobits 0.32.11 
intentions 1.1.5 
language-babel 2.70.2 
linter 2.2.0 
linter-csslint 1.3.4 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-ui-default 1.6.4 
monokai 0.24.0 
open-in-browser 0.5.2 
platformio-ide-terminal 2.5.5 
script-runner 2.2.1 
wakatime 7.0.3 
```

**Comment by saschagehlich** [comment]
This *should* be fixed with 2.5.0, even though I don't exactly know why this is happening. Do you remember the steps you did to cause this?

**Comment by francisngo** [comment]
Whenever I type in a imported file such as `import ReactDOM from 'react-dom'`. At the point where I begin to fill in react-dom or other paths.

UPDATE: I just did an update to 2.5.0 but now I am getting the maximum exceeded (2000).

**Comment by saschagehlich** [comment]
You can increase the maximum file count in `autocomplete-path`'s settings. Closing this for now - if the error persists, please let me know.
