### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by MaoTr** [atom-community/autocomplete-paths#173]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) package 2.12.0

### Stack Trace

Uncaught TypeError: Cannot read property 'push' of undefined

```
At C:\Users\MaoTr\.atom\packages\autocomplete-paths\lib\paths-cache.js:344

TypeError: Cannot read property 'push' of undefined
    at /packages/autocomplete-paths/lib/paths-cache.js:344:18
    at Array.forEach (native)
    at PathsCache._onDidChangeFiles (/packages/autocomplete-paths/lib/paths-cache.js:320:8)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/project.js:297:40
    at PathWatcher.onNativeEvents (~/AppData/Local/atom/app-1.21.0/resources/app/src/path-watcher.js:671:15)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (~/AppData/Local/atom/app-1.21.0/resources/app/src/path-watcher.js:448:26)
    at handler (~/AppData/Local/atom/app-1.21.0/resources/app/src/path-watcher.js:177:15)
```

### Commands

```
  2x -4:59.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  4x -2:25.3.0 core:backspace (input.hidden-input)
  3x -2:21.9.0 core:save (input.hidden-input)
     -0:16.4.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:11.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.12 
autocomplete-modules 1.7.2 
atom-beautify 0.30.5 
atom-react-autocomplete 0.1.10 
react-es6-snippets 0.3.0 
react-snippets 1.0.0 
simplified-chinese-menu 5.3.4 
auto-close-html2 0.6.1 
autocomplete-js-import 1.4.0 
autocomplete-paths 2.12.0 
color-picker 2.2.5 
docblockr 0.11.0 
emmet 1.6.3 
emmet-jsx-css-modules 1.0.0 
git-plus 7.9.3 
Hydrogen 1.23.0 
language-babel 2.75.1 
language-javascript-jsx 0.3.7 
linter 2.0.0 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
minimap 4.29.7 
sync-settings 0.8.3 
```

**Comment by saschagehlich** [comment]
@avaly This is probably related to your file watcher change - could you take a look? :)

**Comment by eviljoe** [comment]
I was able to duplicate this by doing the following:

1. Open a folder in Atom.  My folder structure looked like the one below.
1. Right-click `sub-folder-3` and select "Duplicate"
1. Enter the name of the duplicate and press `Enter`
1. The error above is thrown

Folder Structure
```text/plain
parent-folder
├── sub-folder-1
│   └── file-1.txt
├── sub-folder-2
│   └── file-2.txt
└── sub-folder-3
    └── file-3.txt

```
