### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by vsmawoex** [atom-community/autocomplete-paths#176]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) package 2.12.0

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At C:\Users\vsmawoex\.atom\packages\autocomplete-paths\lib\paths-cache.js:348

TypeError: Cannot read property 'indexOf' of undefined
    at /packages/autocomplete-paths/lib/paths-cache.js:348:28
    at Array.forEach (native)
    at PathsCache._onDidChangeFiles (/packages/autocomplete-paths/lib/paths-cache.js:320:8)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/project.js:297:40
    at PathWatcher.onNativeEvents (~/AppData/Local/atom/app-1.21.0/resources/app/src/path-watcher.js:671:15)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (~/AppData/Local/atom/app-1.21.0/resources/app/src/path-watcher.js:448:26)
    at handler (~/AppData/Local/atom/app-1.21.0/resources/app/src/path-watcher.js:177:15)
```

### Commands

```
     -9:07.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  2x -4:12.8.0 core:backspace (input.hidden-input)
  6x -2:18.3.0 intentions:highlight (input.hidden-input)
     -2:17.7.0 core:save (input.hidden-input)
     -2:13 core:backspace (input.hidden-input)
  2x -2:12 intentions:highlight (input.hidden-input)
     -2:04.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-python-run 0.9.2 
autocomplete-clang 0.11.3 
autocomplete-java 1.2.7 
autocomplete-paths 2.12.0 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
clang-format 1.29.0 
docblockr 0.11.0 
file-icons 2.1.13 
gpp-compiler 3.0.7 
highlight-selected 0.13.1 
Hydrogen 1.23.0 
intentions 1.1.5 
java-generator 2.2.3 
java-importer 1.4.1 
javascript-snippets 1.2.1 
language-javascript-jsx 0.3.7 
language-latex 1.1.1 
latex 0.48.0 
linter 2.2.0 
linter-clang 4.1.2 
linter-flake8 2.2.1 
linter-javac 1.9.4 
linter-python 3.1.2 
linter-ui-default 1.6.10 
markdown-pdf 2.1.0 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
pdf-view 0.59.0 
platformio-ide-terminal 2.7.0 
python-indent 1.1.2 
python-tools 0.6.9 
script 3.17.1 
simplified-chinese-menu 5.3.4 
uncrustify undefined 
```

**Comment by saschagehlich** [comment]
Please try again with autocomplete-paths 2.12.1
