### ISSUE TITLE
Failed to load the autocomplete-paths package

### ISSUE THREAD

**Issue by Bigbigworld86** [atom-community/autocomplete-paths#199]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) package 2.12.2

### Stack Trace

Failed to load the autocomplete-paths package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/autocomplete-paths-master/lib/paths-provider.js:5:24)
    at /packages/autocomplete-paths-master/lib/paths-provider.js:294:46)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/autocomplete-paths-master/lib/autocomplete-paths.js:4:30)
    at /packages/autocomplete-paths-master/lib/autocomplete-paths.js:115:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:937:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
```

### Commands

```
     -0:46.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
file-icons 2.1.15 
atom-beautify 0.30.9 
atom-ternjs 0.18.3 
autoclose-html 0.24.0 
autocomplete-paths 2.12.2 
color-picker 2.2.5 
docblockr 0.13.5 
emmet 2.4.3 
git-plus 7.10.0 
highlight-selected 0.13.1 
linter 2.2.0 
linter-eslint 8.4.0 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
open-in-browser 0.5.2 
sync-settings 0.8.3 
terminal-plus 0.14.5 
tool-bar 1.1.4 
```

**Comment by saschagehlich** [comment]
Looks like you installed `autocomplete-paths` manually by cloning it to your packages folder. Please run `apm install` inside the directory to install its dependencies.

**Comment by m2maomao** [comment]
thks @saschagehlich
