### ISSUE TITLE
`exec("find", ["--version"])` not working with Atom from the Electron 9 PR

### ISSUE THREAD

**Issue by DeeDeeG** [atom-community/autocomplete-paths#254]
### Prerequisites

- [ ] Put an X between the brackets on this line if you have done all of the following:
  - Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
  - Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
  - Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
  - Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
  - Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This line: 

https://github.com/atom-community/autocomplete-paths/blob/ca9566474d4dfea2ad56e5a22004c73165e96423/lib/paths-cache.js#L217

produces an error in the Atom Electron 9 PR build.

`Uncaught (in Promise) TypeError [ERR_INVALID_ARG_VALUE] [ERR_INVALID_ARG_VALUE]: The argument `args` is invalid. Received { maxBuffer: 536870888 }`

(I got the Atom build asset from here: https://github.visualstudio.com/Atom/_build/results?buildId=100414).

### Steps to Reproduce
1. Get Atom Electron 9 PR build (https://github.visualstudio.com/Atom/_build/results?buildId=100414)
2. Install some Atom package that depends on `autocomplete-paths`
3. Bootstrap the Electron 9 PR branch locally.
   i. (Switch to the `electron-upgrade-9.3.5` branch of Atom and apm install/apm rebuild the main node_modules for Electron 9, with the env var `ATOM_RESOURCE_PATH` set to your local Atom repo... (Or do `script/bootstrap --ci`)
4. Launch Atom from the Electron 9 PR.

**Expected behavior:** No errors in console

**Actual behavior:** Error in console `Uncaught (in Promise) TypeError [ERR_INVALID_ARG_VALUE] [ERR_INVALID_ARG_VALUE]: The argument `args` is invalid. Received { maxBuffer: 536870888 }`

**Reproduces how often:** 100% with the Electron 9 PR build

### Versions

`atom --version`:
Atom    : 1.56.0-dev-5bb1df64
Electron: 9.4.1
Chrome  : 83.0.4103.122
Node    : 12.14.1

`apm --version`:
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0-dev-5bb1df64
python 2.7.16
git 2.27.0

- Windows 10 version 20H2 64-bit
- macOS 10.15.7

### Additional Information

~~Doesn't happen outside of Dev Mode~~ Actually, this _does_ happen outside of Dev Mode.

**Comment by DeeDeeG** [comment]
Here is the full error I was seeing:

```
Error: Cannot find module 'atom-ts-transpiler'
Require stack:
- /Users/[user]/.atom/packages/atom-typescript/loader.js
- /Users/[user]/atom/src/module-utils.js
- /Users/[user]/atom/src/package.js
- /Users/[user]/atom/src/package-manager.js
- /Users/[user]/atom/src/atom-environment.js
- /Users/[user]/atom/src/initialize-application-window.js
- /Users/[user]/atom/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/Users/[user]/atom/src/module-cache.js:336:28)
    at Function.require.resolve (/Users/[user]/atom/src/native-compile-cache.js:70:23)
    at Object.<anonymous> (/Users/[user]/.atom/packages/atom-typescript/loader.js:1:188)
    at Object.<anonymous> (/Users/[user]/.atom/packages/atom-typescript/loader.js:8:3)
    at Module._compile (/Users/[user]/atom/src/native-compile-cache.js:120:30)
    at Object.value [as .js] (/Users/[user]/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (/Users/[user]/atom/src/native-compile-cache.js:67:27)
    at requireModule (/Users/[user]/atom/src/module-utils.js:3:17)
    at Package.requireMainModule (/Users/[user]/atom/src/package.js:909:27)
    at Package.activateNow (/Users/[user]/atom/src/package.js:232:34)
    at /Users/[user]/atom/src/package.js:1021:24
    at Function.simpleDispatch (/Users/[user]/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/Users/[user]/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at CommandRegistry.handleCommandEvent (/Users/[user]/atom/src/command-registry.js:379:18)
    at CommandRegistry.dispatch (/Users/[user]/atom/src/command-registry.js:292:17)
    at setupTypeScript (/Users/[user]/.atom/packages/atom-ide-javascript/dist/typescript.js:15:17)
    at /Users/[user]/.atom/packages/atom-ide-javascript/dist/main.js:35:37
```

**Comment by UziTech** [comment]
`exec` doesn't take the arguments in an array like `spawn` the call should be `exec("find --version")`

#256 should fix this

**Comment by DeeDeeG** [comment]
> #256 should fix this

It does for me. Tested by `git clone`ing the package on the `glob` branch, then `pnpm install`ing and `apm link`ing it.

Typing `require('./')` in a JS file shows a path autocompletions view on either branch, but the `glob` branch avoids putting an error in the console.
