### ISSUE TITLE
Uncaught TypeError: Cannot read property 'registerProviderForEditor' of null

### ISSUE THREAD

**Issue by 1ternal** [atom-community/autocomplete-paths#35]
Uncaught TypeError: Cannot read property 'registerProviderForEditor' of null

**Atom Version**: 0.162.0
**System**: linux 3.13.0-43-generic
**Thrown From**: [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) package, v0.9.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

TypeError: Cannot read property 'registerProviderForEditor' of null
  at /home/kev1n/.atom/packages/autocomplete-paths/lib/autocomplete-paths.coffee:27:22
  at /opt/atom/resources/app/src/workspace.js:270:16
  at /opt/atom/resources/app/src/workspace.js:327:18
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/opt/atom/resources/app/src/pane-container.js:379:27)
  at /opt/atom/resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/opt/atom/resources/app/src/pane.js:334:20)
  at Pane.module.exports.Pane.activateItem (/opt/atom/resources/app/src/pane.js:313:14)
  at /opt/atom/resources/app/src/workspace.js:494:16
  at _fulfilled (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:557:44
  at flush (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

/cc @atom/core

**Comment by despairblue** [comment]
Cannot reproduce it in  `atom` `0.166.0-d1c41fb`, `autocomplete-plus` `v1.1.0` and `autocomplete-paths` `v0.9.1`
