### ISSUE TITLE
Preventing file tabs to open

### ISSUE THREAD

**Issue by jgrizou** [atom-community/autocomplete-paths#36]
When I install autocomplete-paths, atom does not open tabs for file anymore.  It says: ``` Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'select-list' ```

I do not see the tabs but when I open the Tabs plugin, disable and enable it, they appear. However they are still not usable, if I open a new file it won't show up.

If I uninstall autocomplete-path, tabs work again.

I am on MacOs Yosemite. I have autocomplete-plus installed and few unrelated plugins: Tasks, Language Latex, Language OpenScad, Latex. I am linking my .atom folder to another folder, but only this computer access it.

Error in console: 
```
Failed to load package named 'autocomplete-plus' Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'select-list'. A type with that name is already registered.
  at Error (native)
  at Object.<anonymous> (/Users/jgrizou/dotfiles/mackup/.atom/packages/autocomplete-plus/lib/select-list-element.coffee:157:47)
  at Object.<anonymous> (/Users/jgrizou/dotfiles/mackup/.atom/packages/autocomplete-plus/lib/select-list-element.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:61:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/jgrizou/dotfiles/mackup/.atom/packages/autocomplete-plus/lib/main.coffee:3:21)
  at Object.<anonymous> (/Users/jgrizou/dotfiles/mackup/.atom/packages/autocomplete-plus/lib/main.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:61:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:599:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:182:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:159:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:173:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:339:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:316:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:602:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:59:25)
 /Applications/Atom.app/Contents/Resources/app/src/package.js:186
```

**Comment by jgrizou** [comment]
Done. Works fine, Thanks!

**Comment by joefitzgerald** [comment]
:thumbsup: thanks for retesting.
