### ISSUE TITLE
Failed to activate the autocomplete-paths package

### ISSUE THREAD

**Issue by KOROKORO-Manbo** [atom-community/autocomplete-paths#74]
came across an error like the below when I put downloaded folder in */.atom/packages/ and run atom

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.10.5
**Thrown From**: [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) package, v1.0.2
### Stack Trace

Failed to activate the autocomplete-paths package

```
At Cannot find module 'fuzzaldrin'

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/UKONN/.atom/packages/autocomplete-paths-master/lib/paths-provider.coffee:2:14)
    at Object.<anonymous> (/Users/UKONN/.atom/packages/autocomplete-paths-master/lib/paths-provider.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.getProvider (/Users/UKONN/.atom/packages/autocomplete-paths-master/lib/autocomplete-paths.coffee:13:21)
    at Object.module.exports.provide (/Users/UKONN/.atom/packages/autocomplete-paths-master/lib/autocomplete-paths.coffee:18:24)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:348:69)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:500:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:483:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-dark-ui",
      "nexus-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
file-type-icons, v0.7.4
linter, v1.11.3
linter-eslint, v6.0.0
minimap, v4.19.0
nexus-syntax, v0.1.1
run-in-browser, v0.1.3

# Dev
No dev packages
```

**Comment by jordanbtucker** [comment]
If you downloaded the package directly, you must `cd` to the `.atom/packages/autocomplete-paths` directory and run `apm install`.

**Comment by Erchoc** [comment]
I hava the problem too，who can tell me what should I  do ?
