### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uploadFolder' of undefined

### ISSUE THREAD

**Issue by AlejikDem** [atom-community/autocomplete-paths#85]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) package, v1.0.2
### Stack Trace

Uncaught TypeError: Cannot read property 'uploadFolder' of undefined

```
At /C:/Users/Oleg/.atom/packages/remote-sync/index.coffee:80

TypeError: Cannot read property 'uploadFolder' of undefined
    at handleEvent (file:///C:/Users/Oleg/.atom/packages/remote-sync/index.coffee:42:3)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-folder (file:///C:/Users/Oleg/.atom/packages/remote-sync/index.coffee:89:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Oleg\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Oleg\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Oleg\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Oleg\AppData\Local\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:1106:28)
    at EventEmitter.outerCallback (C:\Users\Oleg\AppData\Local\atom\app-1.7.3\resources\app.asar\src\application-delegate.js:327:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```
### Commands

```
     -0:36.2.0 core:undo (atom-text-editor.editor.is-focused)
     -0:18.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "about",
      "background-tips",
      "welcome",
      "wrap-guide"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "f:\\Alejik\\OpenServer\\domains\\",
    "themes": [
      "seti-ui",
      "synthcity-atom-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.7
autocomplete-paths, v1.0.2
docblockr, v0.7.3
emmet, v2.4.3
git-diff-details, v1.3.0
git-log, v0.4.1
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
language-babel, v2.18.3
linter, v1.11.4
linter-eslint, v7.2.1
merge-conflicts, v1.4.2
minimap, v4.23.2
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.0
node-debugger, v1.4.7
php-twig, v4.0.0
pigments, v0.26.0
project-manager, v2.9.7
react, v0.15.0
remote-sync, v4.0.1
seti-ui, v0.9.2
synthcity-atom-syntax, v0.2.0

# Dev
No dev packages
```

**Comment by saschagehlich** [comment]
This is probably caused by another package (remote-sync)
